import React from "react";
import type {Metadata} from "next";
import './globals.css'
import Navigation from "@/app/components/Navigation";
import {ThemeProvider} from 'next-themes';
import Footer from "@/app/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <ThemeProvider attribute="class" enableSystem={false}>
      <Navigation />
      {children}
      <Footer />
    </ThemeProvider>
    </body>
    </html>
  );
}